stages:
  - build
  - deploy

build-job:
  tags:
    - blue2
  stage: build
  script:
    - ./gradlew build
  only:
    - master
  artifacts:
    paths:
      - README.md
      - build/libs/tangerine-2.jar