stages:
  - build
  - deploy

build-job:
  tags:
    - blue2
  stage: build
  script:
    - ./gradlew build
    - eval $(ssh-agent -t 5m -s)
    - ssh-add <(echo "$RSYNC_KEY")
    - rsync -auvz -e "ssh" build/reports/ rpeabody@atria.cs.odu.edu:tangerine-2/
    - rsync -auvz -e "ssh" build/docs/ rpeabody@atria.cs.odu.edu:tangerine-2/
    - ssh-agent -k
  only:
    - master
  artifacts:
    paths:
      - README.md
      - build/libs/tangerine-2.jar
